# -*- coding: utf-8 -*-
"""ResNet50.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eFQf9x10nZk3PuSP7B8FWlhijgdVhoto
"""

import tensorflow as tf
from tensorflow.keras.applications.resnet50 import ResNet50
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.resnet50 import preprocess_input,decode_predictions
import numpy as np

model = ResNet50(weights='imagenet')

img_path = input("your_image.jpg=")   # path to your image

img = image.load_img(img_path, target_size=(224, 224))
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)

# preprocess for ResNet
img_array = preprocess_input(img_array)

preds = model.predict(img_array)

decoded = decode_predictions(preds, top=3)

for i, (imagenet_id, label, confidence) in enumerate(decoded[0]):
    print(f"{i+1}. {label}: {confidence:.4f}")

